### ISSUE TITLE
Doesn't seem to work with Rails 3.1.0.rc5

### ISSUE THREAD

**Issue by stevehill1981** [thetron/css3buttons_rails_helpers#16]
The gem doesn't seem to work with Rails 3.1.0.rc5 - I've just tried it in a brand new application here.

I've followed the documentation, as far as adding:

``` ruby
gem 'css3buttons'
```

...to my Gemfile, and adding:

``` ruby
*= require css3buttons
```

...to my app/assets/stylesheets/application.css.

All I get is a Sprockets compilation error, because the file cannot be found. I can see it installed in my system gems, but it would appear that Sprockets isn't looking at those paths.

Any advice for getting this up and running?

**Comment by thetron** [comment]
Dang.

I had tested it on rc4 (i think) before i pushed it back up - I will take a look and see if I can't work out what's wrong. Thanks for the report.

**Comment by stevehill1981** [comment]
Might be Sprockets-related, there have been some reported issues with that on rc4. Going to rc5 fixed my issues with that, but may be the cause here!

**Comment by thetron** [comment]
Yeah, I can confirm this is definitely not working in rc5, but was in rc4. I guess I have some digging to do!

**Comment by thetron** [comment]
Think i've found the problem - just doing some tests.
